load(":phase_aggregation_test.bzl", phase_aggregation_test_suite = "test_suite")
load(":phase_compile_test.bzl", phase_compile_test_suite = "test_suite")
load(":phase_composition_test.bzl", phase_composition_test_suite = "test_suite")
load(":phase_preprocessors_test.bzl", phase_preprocessors_test_suite = "test_suite")
load(":rule_tests.bzl", "test_suite")

test_suite(
    name = "rules_tests",
)

phase_preprocessors_test_suite(
    name = "phase_preprocessors_tests",
)

phase_compile_test_suite(
    name = "phase_compile_tests",
)

phase_aggregation_test_suite(
    name = "phase_aggregation_tests",
)

phase_composition_test_suite(
    name = "phase_composition_tests",
)
