/*
 * Copyright 2026 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package io.bazel.kotlin.builder.cmd

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption
import java.security.MessageDigest
import kotlin.system.exitProcess

/**
 * Pure JVM logic backing the `release_jars` Starlark rule (see design
 * release-jars-stamped-pipeline). The Starlark rule shells out to [main]; the
 * side-effect-free helpers are unit-tested directly.
 */
object ReleaseJars {
  /** A resolved release jar: its download [url] and lowercase-hex [sha256] digest. */
  data class JarEntry(
    val url: String,
    val sha256: String,
  )

  /** Lowercase hex SHA-256 of [bytes]. */
  fun sha256Hex(bytes: ByteArray): String {
    val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
    val sb = StringBuilder(digest.size * 2)
    for (b in digest) {
      val v = b.toInt() and 0xff
      sb.append(HEX[v ushr 4])
      sb.append(HEX[v and 0x0f])
    }
    return sb.toString()
  }

  /** Stable, version-stamped jar file name: `"$name-$version.jar"`. */
  fun stableJarName(
    name: String,
    version: String,
  ): String = "$name-$version.jar"

  /**
   * Parses a Bazel volatile/stable status file, returning the value of [key]
   * from a `KEY value` line. Throws [IllegalArgumentException] if [key] is absent.
   */
  fun parseVersion(
    statusFileText: String,
    key: String,
  ): String {
    for (line in statusFileText.lineSequence()) {
      val trimmed = line.trim()
      if (trimmed.isEmpty()) continue
      val idx = trimmed.indexOf(' ')
      if (idx < 0) continue
      if (trimmed.substring(0, idx) == key) {
        return trimmed.substring(idx + 1).trim()
      }
    }
    throw IllegalArgumentException("status file has no entry for key '$key'")
  }

  /**
   * Renders a deterministic (sorted-key) Starlark file declaring the release
   * jar table and version. Sorted keys keep the output reproducible.
   */
  fun renderJarVersionBzl(
    version: String,
    jars: Map<String, JarEntry>,
  ): String {
    val sb = StringBuilder()
    sb.append("\"\"\"Generated by ReleaseJars. Do not edit.\"\"\"\n\n")
    sb.append("JARS = {\n")
    for (name in jars.keys.sorted()) {
      val entry = jars.getValue(name)
      sb.append("    \"").append(name).append("\": struct(")
      sb.append("url = \"").append(entry.url).append("\", ")
      sb.append("sha256 = \"").append(entry.sha256).append("\"),\n")
    }
    sb.append("}\n\n")
    sb.append("VERSION = \"").append(version).append("\"\n")
    return sb.toString()
  }

  /** CLI entry point for the `release_jars` rule; exits with [run]'s status code. */
  @JvmStatic
  fun main(args: Array<String>) {
    exitProcess(run(args))
  }

  /** Parses CLI flags, hashes and copies each jar, then writes the rendered jar_version.bzl. */
  private fun run(args: Array<String>): Int {
    var versionFile: String? = null
    var versionKey: String? = null
    var outBzl: String? = null
    var outDir: String? = null
    val jarPaths = LinkedHashMap<String, String>()
    val urlTemplates = LinkedHashMap<String, String>()

    var i = 0
    while (i < args.size) {
      val flag = args[i]

      fun next(): String {
        i++
        require(i < args.size) { "flag '$flag' requires an argument" }
        return args[i]
      }

      when (flag) {
        "--version_file" -> {
          versionFile = next()
        }

        "--version_key" -> {
          versionKey = next()
        }

        "--out_bzl" -> {
          outBzl = next()
        }

        "--out_dir" -> {
          outDir = next()
        }

        "--jar" -> {
          val (name, path) = splitKeyValue(next())
          jarPaths[name] = path
        }

        "--url" -> {
          val (name, template) = splitKeyValue(next())
          urlTemplates[name] = template
        }

        else -> {
          throw IllegalArgumentException("unknown flag: $flag")
        }
      }
      i++
    }

    val resolvedVersionFile = requireNotNull(versionFile) { "--version_file is required" }
    val resolvedVersionKey = requireNotNull(versionKey) { "--version_key is required" }
    val resolvedOutBzl = requireNotNull(outBzl) { "--out_bzl is required" }
    val resolvedOutDir = requireNotNull(outDir) { "--out_dir is required" }

    val version =
      parseVersion(
        Files.readString(Paths.get(resolvedVersionFile)),
        resolvedVersionKey,
      )

    val outDirPath = Paths.get(resolvedOutDir)
    Files.createDirectories(outDirPath)

    val entries = LinkedHashMap<String, JarEntry>()
    for ((name, path) in jarPaths) {
      val jarPath = Paths.get(path)
      val sha256 = sha256Hex(Files.readAllBytes(jarPath))
      val template = urlTemplates[name] ?: ""
      val url =
        template
          .replace("{version}", version)
          .replace("{name}", name)
      entries[name] = JarEntry(url, sha256)
      copyTo(jarPath, outDirPath.resolve(stableJarName(name, version)))
    }

    Files.writeString(Paths.get(resolvedOutBzl), renderJarVersionBzl(version, entries))
    return 0
  }

  /** Copies [source] to [target], overwriting any existing file. */
  private fun copyTo(
    source: Path,
    target: Path,
  ) {
    Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING)
  }

  /** Splits a `name=value` CLI argument into its (name, value) pair; requires a non-empty name. */
  private fun splitKeyValue(arg: String): Pair<String, String> {
    val idx = arg.indexOf('=')
    require(idx > 0) { "expected name=value but got '$arg'" }
    return arg.substring(0, idx) to arg.substring(idx + 1)
  }

  private val HEX = "0123456789abcdef".toCharArray()
}
